name: Tesstial
author: TAQU
version: 1.0
main: tessential.main.Main

commands:
   globalmute:
    aliases: [gm]
   cc:
    aliases: [clearchat]
   fly:
    aliases: [fliegen]
   day:
    aliases: [tag]
   night:
    aliases: [nacht]
   reaload:
    aliases: [rl]
   rain:
    aliases: [regen]
   sun:
    aliases: [sonne]